"""
Pos tags descriptions
"""
def pos_dict_en():
    """
    Source:
    Taylor, Ann & Marcus, Mitchell & Santorini, Beatrice. (2003).
    The Penn Treebank: An overview. 10.1007/978-94-010-0201-1_1. 
    """

    return {'CC': 'Coordinating conj.',
            'TO': 'Infinitival "to"',
            'CD': 'Cardinal number',
            'UH': 'Interjection',
            'DT': 'Determiner',
            'VB': 'Verb (base form)',
            'EX': 'Existential there',
            'VBD': 'Verb (past tense)',
            'FW': 'Foreign word',
            'VBG': 'Verb (gerund/present pple)',
            'IN': 'Preposition',
            'VBN': 'Verb (past participle)',
            'JJ': 'Adjective',
            'VBP': 'Verb (non-3rd ps. sg. present)',
            'JJR': 'Adjective (comparative)',
            'VBZ': 'Verb (3rd ps. sg. present)',
            'JJS': 'Adjective (superlative)',
            'WDT': 'Wh-determiner',
            'LS': 'List item marker',
            'WP': 'Wh-pronoun',
            'MD': 'Modal',
            'WP$': 'Possessive wh-pronoun',
            'NN': 'Noun (singular or mass)',
            'WRB': 'Wh-adverb',
            'NNS': 'Noun (plural)',
            '#': 'Pound sign',
            'NNP': 'Proper noun, singular',
            '$': 'Dollar sign',
            'PRP$': 'Possessive pronoun',
            'NNPS': 'Proper noun (plural)',
            '.': 'Sentence-final punctuation',
            'PDT': 'Predeterminer', 
            ',': 'Comma',
            'P': 'OS Possessive ending',
            ':': 'Colon / semi-colon',
            'PRP': 'Personal pronoun',
            '(': 'Left bracket character',
            'PP$': 'Possessive pronoun',
            ')': 'Right bracket character',
            'RB': 'Adverb',
            '"': 'Straight double quote',
            'RBR': 'Adverb (comparative)',
            '‘': 'Left open single quote',
            'RBS': 'Adverb (superlative)',
            '“': 'Left open double quote',
            'RP': 'Particle',
            '’': 'Right close single quote',
            'SYM': 'Symbol',
            '”': 'Right close double quo',
            '<s>': 'Start of sentence',
            'POS': 'POS',
            '``': '``',
            '-NONE-': 'None',
            '</s>': 'End of sentence',
            '<UNK>': 'Unknown',
            "''": 'Empty tag'
            }
